Resolve Sidekiq Feedback
jherdman/active_jorb pull request #21
Opened 2018-04-17 17:48 UTC by jherdman

Resolves #19

2018-04-17 18:06 UTC, elucid requested changes

2018-04-17 18:06 UTC, elucid commented on lib/active_jorb/job.ex
> +            job_id: ""
IMO this should be `nil`

2018-04-17 18:06 UTC, elucid commented on lib/active_jorb/job.ex
> +          job_id: String.t()
And this should be `nil | String.t()`

2018-04-17 18:11 UTC, jherdman commented on lib/active_jorb/job.ex
> +          job_id: String.t()
Done!

2018-04-17 19:07 UTC, jherdman commented
@elucid should be fixed

2018-04-23 16:44 UTC, elucid commented
Hey @jherdman sorry for taking so long to get to this. I just took a look and the payload is missing `job_id`. It looks like the above only modifies what `ActiveJorb.QueueAdapter.Sidekiq.enqueue_at/2` but not `ActiveJorb.QueueAdapter.Sidekiq.enqueue/1`.

While adding the job_id within the body of `ActiveJorb.QueueAdapter.Sidekiq.enqueue/1` is an easy fix, I wonder if there isn't a better place to put this that both `ActiveJorb.QueueAdapter.Sidekiq.enqueue/1` and `ActiveJorb.QueueAdapter.Sidekiq.enqueue_at/2` could make use of. AFAICT there isn't a way to have Elixir structs properties dynamically initialized by functions.

2018-04-23 20:50 UTC, jherdman commented
@elucid a little bit better. Back at ya.

2018-04-24 15:48 UTC, elucid commented
Thanks.

I think this is good for now--I've tested again. Feel free to merge and cut a release.

In the future, maybe we should consider using factory functions like Lance Halvorsen suggests in "Functional Web Development with Elixir, OTP, and Phoenix"

2018-04-24 15:49 UTC, elucid approved these changes

2018-04-24 17:39 UTC, merged